[package]
name = "solver-bruteforce-hole"
version = "0.1.0"
authors = ["skobochka"]
edition = "2018"

[dependencies]
common = { path = "../../common" }
log = "^0.4"
structopt = "^0.3"
pretty_env_logger = "^0.4"
