[package]
name = "app"
version = "0.6.2"
authors = ["skobochka"]
edition = "2018"

[dependencies]
common = { path = "../common" }

log = "^0.4"
geo = "^0.18"
structopt = "^0.3"
piston_window = "^0.120"
pretty_env_logger = "^0.4"
