[package]
name = "common"
version = "0.2.1"
authors = ["skobochka"]
edition = "2018"

[dependencies]
log = "^0.4"
serde = "^1.0"
structopt = "^0.3"
serde_json = "^1.0"
serde_derive = "^1.0"
geo = "^0.18"
