[package]
name = "common"
version = "0.5.1"
authors = ["skobochka"]
edition = "2018"

[dependencies]
log = "^0.4"
rand = "^0.8"
serde = "^1.0"
bit-vec = "^0.6"
structopt = "^0.3"
serde_json = "^1.0"
serde_derive = "^1.0"
geo = "^0.18"
